# Generated by Django 2.2.3 on 2019-07-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_email'),
        ('cadastrotratamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(choices=[{'INCISIVO CENTRAL SUPERIOR', '11'}, {'INCISIVO CENTRAL SUPERIOR', '21'}, {'INCISIVO LATERAL SUPERIOR', '12'}, {'INCISIVO LATERAL SUPERIOR', '22'}, {'13', 'CANINO SUPERIOR'}, {'23', 'CANINO SUPERIOR'}, {'14', 'PRE MOLAR SUPERIOR'}, {'PRE MOLAR SUPERIOR', '15'}, {'PRE MOLAR SUPERIOR', '24'}, {'PRE MOLAR SUPERIOR', '25'}, {'16', 'MOLAR SUPERIOR'}, {'MOLAR SUPERIOR', '17'}, {'18', 'MOLAR SUPERIOR'}, {'26', 'MOLAR SUPERIOR'}, {'MOLAR SUPERIOR', '27'}, {'28', 'MOLAR SUPERIOR'}, {'INCISIVO CENTRAL INFERIOR', '31'}, {'INCISIVO CENTRAL INFERIOR', '41'}, {'INCISIVO LATERAL INFERIOR', '32'}, {'INCISIVO LATERAL INFERIOR', '42'}, {'CANINO INFERIOR', '33'}, {'CANINO INFERIOR', '43'}, {'34', 'PRE MOLAR INFERIOR'}, {'PRE MOLAR INFERIOR', '35'}, {'PRE MOLAR INFERIOR', '44'}, {'PRE MOLAR INFERIOR', '45'}, {'36', 'MOLAR INFERIOR'}, {'37', 'MOLAR INFERIOR'}, {'MOLAR INFERIOR', '38'}, {'46', 'MOLAR INFERIOR'}, {'MOLAR INFERIOR', '47'}, {'48', 'MOLAR INFERIOR'}], max_length=60, verbose_name='Dente')),
                ('observacao', models.CharField(max_length=5000, verbose_name='Observação')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('id_tratamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastrotratamento.CadastroTratamento')),
            ],
        ),
    ]
