# Generated by Django 2.2.3 on 2019-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamento',
            options={'verbose_name': 'Tratamento', 'verbose_name_plural': 'Tratamentos'},
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='id_tratamento',
            new_name='nometratamento',
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='dente',
            field=models.CharField(choices=[('0-TODOS', 'TODOS'), ('11-INCISIVO CENTRAL SUPERIOR', 'INCISIVO CENTRAL SUPERIOR'), ('21-INCISIVO CENTRAL SUPERIOR', 'INCISIVO CENTRAL SUPERIOR'), ('12-INCISIVO LATERAL SUPERIOR', 'INCISIVO LATERAL SUPERIOR'), ('22-INCISIVO LATERAL SUPERIOR', 'INCISIVO LATERAL SUPERIOR'), ('13-CANINO SUPERIOR', 'CANINO SUPERIOR'), ('23-CANINO SUPERIOR', 'CANINO SUPERIOR'), ('14-PRE-MOLAR SUPERIOR', 'PRE-MOLAR SUPERIOR'), ('15-PRE-MOLAR SUPERIOR', 'PRE-MOLAR SUPERIOR'), ('24-PRE-MOLAR SUPERIOR', 'PRE-MOLAR SUPERIOR'), ('25-PRE-MOLAR SUPERIOR', 'PRE-MOLAR SUPERIOR'), ('16-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('17-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('18-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('26-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('27-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('28-MOLAR SUPERIOR', 'MOLAR SUPERIOR'), ('31-INCISIVO CENTRAL INFERIOR', 'INCISIVO CENTRAL INFERIOR'), ('41-INCISIVO CENTRAL INFERIOR', 'INCISIVO CENTRAL INFERIOR'), ('32-INCISIVO LATERAL INFERIOR', 'INCISIVO LATERAL INFERIOR'), ('42-INCISIVO LATERAL INFERIOR', 'INCISIVO LATERAL INFERIOR'), ('33-CANINO INFERIOR', 'CANINO INFERIOR'), ('43-CANINO INFERIOR', 'CANINO INFERIOR'), ('34-PRE MOLAR INFERIOR', 'PRE MOLAR INFERIOR'), ('35-PRE MOLAR INFERIOR', 'PRE MOLAR INFERIOR'), ('44-PRE MOLAR INFERIOR', 'PRE MOLAR INFERIOR'), ('45-PRE MOLAR INFERIOR', 'PRE MOLAR INFERIOR'), ('36-MOLAR INFERIOR', 'MOLAR INFERIOR'), ('37-MOLAR INFERIOR', 'MOLAR INFERIOR'), ('38-MOLAR INFERIOR', 'MOLAR INFERIOR'), ('46-MOLAR INFERIOR', 'MOLAR INFERIOR'), ('47-MOLAR INFERIOR', 'MOLAR INFERIOR'), ('48-MOLAR INFERIOR', 'MOLAR INFERIOR')], max_length=60, verbose_name='Dente'),
        ),
    ]
