# Generated by Django 2.2.3 on 2019-07-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrotratamento', '0003_auto_20190706_1136'),
        ('tratamento', '0002_auto_20190706_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamento',
            name='nometratamento',
        ),
        migrations.AddField(
            model_name='tratamento',
            name='tratamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastrotratamento.CadastroTratamento', verbose_name='Tratamento'),
        ),
    ]
