# Generated by Django 2.2.3 on 2019-08-06 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0004_auto_20190706_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='data_tratamento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Tratamento'),
        ),
    ]
