# Generated by Django 3.0.3 on 2020-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamento', '0005_tratamento_data_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='valor_tratamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor'),
        ),
    ]
