language: python
dist: xenial
sudo: true

python:
  - 3.7

env:
  global:
    - PIPENV_VENV_IN_PROJECT = 1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync -d
  - cp contrib/env_sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest
  - pipenv run pytest --cov=controledental

after_success:
  - pipenv run codecov