# Generated by Django 2.2.1 on 2019-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(max_length=25)),
                ('cpf', models.CharField(max_length=25)),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=25, verbose_name='Telefone')),
                ('observacao', models.CharField(max_length=2000, verbose_name='Observações')),
                ('alergia', models.CharField(max_length=100, verbose_name='Alergias')),
                ('medicamentos', models.CharField(max_length=500, verbose_name='Medicamentos')),
                ('historico_cirurgias', models.CharField(max_length=2000, verbose_name='Cirurgias')),
            ],
        ),
    ]
