# Generated by Django 2.2.3 on 2019-07-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
