# Generated by Django 3.0.3 on 2020-02-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
