# Generated by Django 3.0.3 on 2020-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200226_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alergia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='historico_cirurgias',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Cirurgias'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicamentos',
            field=models.CharField(blank=True, max_length=500, verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='observacao',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rg',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefone'),
        ),
    ]
