# Generated by Django 2.2.3 on 2019-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tratamento', models.CharField(max_length=200, verbose_name='Tratamento')),
                ('observacao', models.CharField(max_length=2000, verbose_name='Observações')),
            ],
        ),
    ]
