# Generated by Django 3.0.3 on 2020-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tratamento', models.CharField(max_length=200, verbose_name='Nome Tratamento')),
                ('valor_tratamento', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor')),
                ('observacao', models.CharField(default=None, max_length=2000, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cadastro Tratamento',
                'verbose_name_plural': 'Cadastro de tratamentos',
            },
        ),
    ]
