# Generated by Django 2.2.3 on 2019-07-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrotratamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotratamento',
            name='observacao',
            field=models.CharField(default=None, max_length=2000, verbose_name='Observações'),
        ),
    ]
