# Generated by Django 2.2.3 on 2019-07-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrotratamento', '0002_auto_20190705_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrotratamento',
            options={'verbose_name': 'Cadastro Tratamento', 'verbose_name_plural': 'Cadastro de tratamentos'},
        ),
        migrations.AlterField(
            model_name='cadastrotratamento',
            name='nome_tratamento',
            field=models.CharField(max_length=200, verbose_name='Nome Tratamento'),
        ),
    ]
