# Generated by Django 3.0.3 on 2020-02-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrotratamento', '0003_auto_20190706_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrotratamento',
            name='valor_tratamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor'),
        ),
    ]
